### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Murryy79** [krujos/download_droplet_plugin#4]
I was successfully able to download droplet from PCF 1.10 
Getting this error when downloading droplet from PCF 1.7

[root@vclp003858 CAS-download_droplet_plugin]# cf download-droplet orionncsdatarest-vsto-green orionncsdatarest-vsto-green.1.7.tar
2017/09/14 12:17:24 Downloader = &{0xc820011510 0xa13f58}
Saving orionncsdatarest-vsto-green's droplet to orionncsdatarest-vsto-green.1.7.tar
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x480a77]

goroutine 1 [running]:
github.com/krujos/download_droplet_plugin/droplet.(*CFDownloader).GetDroplet(0xc820013240, 0xc8200d9380, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/droplet/downloader.go:76 +0x827
github.com/krujos/download_droplet_plugin/droplet.(*CFDroplet).SaveDroplet(0xc8200132a0, 0x7ffd59be9764, 0x1b, 0x7ffd59be9780, 0x23, 0x0, 0x0)
        /Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/droplet/droplet.go:36 +0xda
github.com/krujos/download_droplet_plugin/command.(*DownloadDropletCmd).Run(0xc8200131c0, 0x7f81718f09e8, 0xc820011510, 0xc82000a0c0, 0x3, 0x3)
        /Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/command/download_droplet_cmd.go:92 +0x454
github.com/cloudfoundry/cli/plugin.Start(0x7f81718ef8f8, 0xc8200131c0)
        /Users/jkruck/go/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:30 +0x400
github.com/krujos/download_droplet_plugin/command.(*DownloadDropletCmd).Start(0xc8200131c0)
        /Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/command/download_droplet_cmd.go:105 +0x48
main.main()
        /Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/main.go:7 +0x112
[root@vclp003858 CAS-download_droplet_plugin]#

**Comment by AnandDivakaran** [comment]
I'm facing the same error. Any suggestions on how to get this resolved ?

**Comment by WenlongWang** [comment]
I'm facing the same error，in my case, it's because  cloud foundry redirect me to the s3 url. and s3 url is not resolved on my client host.  Configuring s3 url in  /etc/hosts solves my problem
