### ISSUE TITLE
unexpected signal during runtime execution?

### ISSUE THREAD

**Issue by bobbyhubbard** [krujos/download_droplet_plugin#6]
Currently running cf version 6.34.1+bbdf81482.2018-01-17 on OSx

dr:~/dev/temp\ $ cf download-droplet prod-itdevice-marineProcessServices-3 ./test.tar
1969/12/31 18:00:00 Downloader = &{0xc8200f81a0 0x614b18} 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xae090]

goroutine 1 [running]:
runtime.throw(0x475b40, 0x2a)
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:527 +0x90 fp=0xc820107a30 sp=0xc820107a18
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc820107a80 sp=0xc820107a30
sync.(*Pool).Get(0x5ef690, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/sync/pool.go:101 +0x40 fp=0xc820107ad0 sp=0xc820107a80
fmt.newPrinter(0x3298)
	/usr/local/Cellar/go/1.5.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc820107b10 sp=0xc820107ad0
fmt.Fprintf(0x14a43b8, 0xc82002c010, 0x44c160, 0x1a, 0xc820107cd8, 0x2, 0x2, 0xd2e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/fmt/print.go:187 +0x30 fp=0xc820107b58 sp=0xc820107b10
fmt.Printf(0x44c160, 0x1a, 0xc820107cd8, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/fmt/print.go:197 +0x94 fp=0xc820107bc0 sp=0xc820107b58
github.com/krujos/download_droplet_plugin/command.(*DownloadDropletCmd).Run(0xc8200fc140, 0x1591260, 0xc8200f81a0, 0xc82000a1b0, 0x3, 0x3)
	/Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/command/download_droplet_cmd.go:91 +0x3f9 fp=0xc820107d00 sp=0xc820107bc0
github.com/cloudfoundry/cli/plugin.Start(0x1590170, 0xc8200fc140)
	/Users/jkruck/go/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:30 +0x400 fp=0xc820107e88 sp=0xc820107d00
github.com/krujos/download_droplet_plugin/command.(*DownloadDropletCmd).Start(0xc8200fc140)
	/Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/command/download_droplet_cmd.go:105 +0x48 fp=0xc820107ec8 sp=0xc820107e88
main.main()
	/Users/jkruck/go/src/github.com/krujos/download_droplet_plugin/main.go:7 +0x112 fp=0xc820107f40 sp=0xc820107ec8
runtime.main()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc820107f90 sp=0xc820107f40
runtime.goexit()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820107f98 sp=0xc820107f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1

**Comment by jghiloni** [comment]
Hey @bobbyhubbard I'm working on a fix for this! Temporarily, if you want to just rebuild it with the latest version of Go, it'll work.

**Comment by bobbyhubbard** [comment]
@jghiloni Hey! "The Canadian" is sitting next to me...says 'suwrry'. :) Thanks for the update

**Comment by alexvasseur** [comment]
same with cf version 6.36
rebuilding from source works for me (using go version go1.9.1 darwin/amd64)

**Comment by jghiloni** [comment]
Hey @bobbyhubbard still working on getting this in ... the rebuild is effectively the fix though. Just trying to get some more tests in before it gets integrated.
